variable "github_token" {
  type = string
  description = "This is the personal GITHUB token generated by org owner."
}

variable "github_organization" {
  type = string
  description = "This is the personal GITHUB token generated by org owner."
}